# Generated by Django 3.0.5 on 2021-05-02 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpendTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '"data"."spend_types"',
            },
        ),
        migrations.CreateModel(
            name='Spends',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('spend_type', models.ForeignKey(db_column='spend_type', on_delete=django.db.models.deletion.CASCADE, to='spendings.SpendTypes')),
            ],
            options={
                'db_table': '"data"."spends"',
            },
        ),
    ]
