version: "3"
services:
  postgres:
    image: "postgres"
    container_name: "postgres"
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    #volumes:
    #  - ./postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: 'pgadmin'
    #restart: always
    env_file:
      - ./.env
    ports:
      - "8084:80"
    depends_on:
      - postgres

  backend:
    image: my-django
    build: ./django-backend/.
    container_name: backend
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - ./django-backend/app/:/opt/
    command: sh -c "sleep 5 && python manage.py makemigrations && python manage.py migrate && ./initAdmin.sh && python manage.py runserver 0.0.0.0:8000"
    