# Generated by Django 3.0.5 on 2020-10-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='next_payment',
            field=models.DateTimeField(null=True),
        ),
    ]
