# Generated by Django 3.0.5 on 2020-10-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_auto_20201013_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='open_date',
            field=models.DateTimeField(null=True),
        ),
    ]
