# Generated by Django 3.0.5 on 2020-10-06 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '"data"."income_types"',
            },
        ),
        migrations.CreateModel(
            name='Incomes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('income_type', models.ForeignKey(db_column='income_type', on_delete=django.db.models.deletion.CASCADE, to='incomes.IncomeTypes')),
            ],
            options={
                'db_table': '"data"."incomes"',
            },
        ),
    ]
